### ISSUE TITLE
e.which is deprecated

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/fewpjs-acting-on-events#1]
[KeyboardEvent.which is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) and should be replaced with [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).

**Comment by AspenJames** [comment]
This will require a small rewrite of the content, as well as a change in the images shown to reflect using `e.key` returning `ArrowLeft` instead of `e.which` returning `37`.

**Comment by sgharms** [comment]
@AspenJames Added two new PRs: 

#3  and #2 

Please verify and I will merge.

**Comment by AspenJames** [comment]
@sgharms Looks great, thank you!
